# Generated by Django 3.1.7 on 2021-04-02 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='specialRole',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='typeAccount',
            field=models.CharField(choices=[('STUDENT', 'STUDENT'), ('CATERER', 'CATERER'), ('GUEST', 'GUEST')], max_length=20),
        ),
    ]
