# Generated by Django 3.1.7 on 2021-03-09 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('bill', 'bill'), ('coupon', 'coupon')], max_length=10)),
            ],
        ),
    ]
