# Generated by Django 3.1.7 on 2021-03-26 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_auto_20210326_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_from',
            field=models.DateField(),
        ),
    ]
