# Generated by Django 3.1.7 on 2021-03-26 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='body',
            field=models.TextField(default='Sample'),
            preserve_default=False,
        ),
    ]
