# Generated by Django 3.1.7 on 2021-03-25 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='status',
            new_name='resolved',
        ),
    ]
