# Generated by Django 3.1.7 on 2021-04-02 06:09

import complaints.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_auto_20210325_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='applied_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complaint',
            name='resolved_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to=complaints.models.Complaint.user_directory_path),
        ),
    ]
